---
- name: "install plugins"
  command: "bash -lc 'asdf plugin-add {{ item.name }} {{ item.repository | default() }}'"
  args:
    creates: "{{ asdf_user_home }}/.asdf/plugins/{{ item.name }}"
    chdir: "{{ asdf_user_home }}"
  with_items: "{{ asdf_plugins }}"
  when: asdf_plugins|length > 0
  become: True
  become_user: "{{ user }}"
  ignore_errors: True

- name: "nodejs specific tasks"
  include_tasks: "nodejs.yml"
  when: '"nodejs" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "install apps"
  command: "bash -lc 'asdf install {{ item.0.name }} {{ item.1 }}'"
  args:
    creates: "{{ asdf_user_home }}/.asdf/installs/{{ item.0.name }}/{{ item.1 }}"
    chdir: "{{ asdf_user_home }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True
  when: asdf_plugins|length > 0
  become: True
  become_user: "{{ user }}"

- name: "uninstall apps"
  command: "bash -lc 'asdf uninstall {{ item.0.name }} {{ item.1 }}'"
  args:
    removes: "{{ asdf_user_home }}/.asdf/installs/{{ item.0.name }}/{{ item.1 }}"
    chdir: "{{ asdf_user_home }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - delete_versions
    - flags:
      skip_missing: True
  when: asdf_plugins|length > 0
  become: True
  become_user: "{{ user }}"

- name: "set global app versions"
  command: "bash -lc 'asdf global {{ item.name }} {{ item.global }}'"
  args:
    chdir: "{{ asdf_user_home }}"
  when: item.versions is defined
  with_items: "{{ asdf_plugins }}"
  become: True
  become_user: "{{ user }}"

- name: "set asdfrc"
  template:
    src: "asdfrc.j2"
    dest: "{{ asdf_user_home }}/.asdfrc"
    owner: "{{ user }}"
    mode: 0644
  become: True
  become_user: "{{ user }}"
